Start tracking metrics
deardurham/dear-petition pull request #248
Opened 2021-11-15 05:47 UTC by georgehelman

2021-11-15 05:50 UTC, georgehelman commented
https://github.com/deardurham/dear-petition/issues/247

2021-11-23 23:37 UTC, robert-w-gries requested changes

2021-11-23 23:37 UTC, robert-w-gries commented on .eslintrc.json
> +      "endOfLine": "auto"
This should be removed

2021-11-23 23:37 UTC, robert-w-gries commented on .gitattributes
> +*.js text eol=lf
`* text=auto eol=lf`

2021-11-23 23:37 UTC, robert-w-gries commented on .prettierrc
> +  "endOfLine": "auto",
remove endOfLine

2021-12-07 23:11 UTC, copelco reviewed
Looks good! Added a few comments. I think adding a `GeneratedPetitionAdmin` could also be helpful to easily show the data that's being tracked.

2021-12-07 23:11 UTC, copelco commented on dear_petition/petition/models.py
> +    batch = models.ForeignKey(Batch, on_delete=models.DO_NOTHING)
I think `models.DO_NOTHING` will end up raising an IntegrityError when `Batch` objects are deleted nightly:

```suggestion
    batch_id = models.PositiveIntegerField()
```

2021-12-07 23:11 UTC, copelco commented on dear_petition/petition/models.py
> +    user = models.ForeignKey(
Maybe this could be `username` so we preserve history if a user is deleted?

2021-12-07 23:11 UTC, copelco commented on dear_petition/users/models.py
> +    last_generated_petition_time = DateField(null=True)
Is `last_generated_petition_time` used somewhere?

2021-12-12 20:49 UTC, copelco approved these changes
Looks good to me :shipit:

2021-12-12 20:49 UTC, merged