Add age, county, jurisdiction, race, sex, and county to tracked metrics
deardurham/dear-petition pull request #273
Opened 2022-01-23 01:17 UTC by georgehelman

2022-01-23 01:19 UTC, georgehelman commented
https://github.com/deardurham/dear-petition/issues/265

2022-02-01 23:37 UTC, copelco commented on dear_petition/petition/models.py
>      batch_id = models.PositiveIntegerField()
I'd suggest making all of the new fields read-only in the admin, so these values can't be modified.

2022-02-02 00:00 UTC, robert-w-gries requested changes
Is there any testing for the statistics yet? I think that could be a good addition if it won't take too much time. Otherwise, we can split it out to a new ticket

2022-02-06 21:14 UTC, robert-w-gries approved these changes

2022-02-15 22:53 UTC, georgehelman commented
I'll split it into a new issue.

2022-02-15 22:53 UTC, merged

2022-02-15 22:54 UTC, georgehelman commented
https://github.com/deardurham/dear-petition/issues/280